### ISSUE TITLE
Crash when no databases exist

### ISSUE THREAD

**Issue by dotancohen** [dotancohen/burton#11]
```
 5. Configure databases
>> 5

 1. Add/Remove database
>> 1

Manage databases

Available databases:
Traceback (most recent call last):
  File "./burton.py", line 108, in <module>
    main(sys.argv)
  File "./burton.py", line 86, in main
    configure_databases.main(env)
  File "/home/dotancohen/burton/configure_databases.py", line 41, in main
    manage_databases()
  File "/home/dotancohen/burton/configure_databases.py", line 71, in manage_databases
    new_db_index = index + 1
UnboundLocalError: local variable 'index' referenced before assignment
```

**Comment by dotancohen** [comment]
The previous commit may or may not resolve the issue. Please triage on a machine with no databases configured.
